In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.546833395', '0.397780857', '0.258516774'],
 'mae score': ['105,152.662220', '112,802.230878', '135,341.856941'],
 'mse score': ['27,593,804,658.024490',
  '36,615,458,386.624649',
  '45,078,630,733.622131'],
 'r2 score': ['0.545599', '0.397035', '0.257668'],
 'mean fit time': [0.003127765655517578,
  0.00556478500366211,
  0.006261062622070312]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.327020996', '0.381263855'],
 'mae score': ['128,653.643522', '126,328.553824'],
 'mse score': ['40,997,915,243.527130', '37,599,952,321.604591'],
 'r2 score': ['0.324867', '0.380823'],
 'mean fit time': [0.00312957763671875, 0.0015103340148925782]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.487216276',
  '0.381177504',
  '0.485365557',
  '0.381177504'],
 'mae score': ['110,056.754757',
  '124,270.392120',
  '110,170.799824',
  '124,270.392120'],
 'mse score': ['31,196,184,216.055710',
  '37,623,616,692.525902',
  '31,309,882,968.078270',
  '37,623,616,692.525902'],
 'r2 score': ['0.486277', '0.380433', '0.484405', '0.380433'],
 'mean fit time': [0.0050776004791259766,
  0.0016237258911132812,
  0.0016095161437988282,
  0.0]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model'],
 'explained variance score': ['0.477376898',
  '0.368437940',
  '0.477365692',
  '0.368437940'],
 'mae score': ['112,647.010554',
  '127,261.453282',
  '112,454.557622',
  '127,261.453282'],
 'mse score': ['31,828,239,077.176872',
  '38,431,831,503.248024',
  '31,826,803,078.687500',
  '38,431,831,503.248024'],
 'r2 score': ['0.475868', '0.367124', '0.475892', '0.367124'],
 'mean fit time': [0.008438348770141602,
  0.004640722274780273,
  0.003343534469604492,
  0.00114288330078125]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.487109955',
  '0.381049321',
  '0.476988689',
  '0.381049321'],
 'mae score': ['110,035.423980',
  '124,268.363864',
  '110,910.511834',
  '124,268.363864'],
 'mse score': ['31,202,709,904.601429',
  '37,631,453,434.768959',
  '31,820,010,647.515808',
  '37,631,453,434.768959'],
 'r2 score': ['0.486169', '0.380304', '0.476004', '0.380304'],
 'mean fit time': [0.0027376651763916016,
  0.0028038501739501955,
  0.002939128875732422,
  0.0]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree Best Params,0.546833395,"105,152.662220","27,593,804,658.024490",0.545599,0.003128
Recursive Feature Elimination,0.397780857,"112,802.230878","36,615,458,386.624649",0.397035,0.005565
Sequential Feature Selector,0.258516774,"135,341.856941","45,078,630,733.622131",0.257668,0.006261

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.327020996,"128,653.643522","40,997,915,243.527130",0.324867,0.00313
Sequential Feature Selector,0.381263855,"126,328.553824","37,599,952,321.604591",0.380823,0.00151

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.487216276,"110,056.754757","31,196,184,216.055710",0.486277,0.005078
Select From Model,0.381177504,"124,270.392120","37,623,616,692.525902",0.380433,0.001624
Sequential Feature Selector,0.485365557,"110,170.799824","31,309,882,968.078270",0.484405,0.001610
Recursive Feature Elimination,0.381177504,"124,270.392120","37,623,616,692.525902",0.380433,0.000000

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.477376898,"112,647.010554","31,828,239,077.176872",0.475868,0.008438
Recursive Feature Elimination,0.368437940,"127,261.453282","38,431,831,503.248024",0.367124,0.004641
Sequential Feature Selector,0.477365692,"112,454.557622","31,826,803,078.687500",0.475892,0.003344
Select From Model,0.368437940,"127,261.453282","38,431,831,503.248024",0.367124,0.001143

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.487109955,"110,035.423980","31,202,709,904.601429",0.486169,0.002738
Select From Model,0.381049321,"124,268.363864","37,631,453,434.768959",0.380304,0.002804
Sequential Feature Selector,0.476988689,"110,910.511834","31,820,010,647.515808",0.476004,0.002939
Recursive Feature Elimination,0.381049321,"124,268.363864","37,631,453,434.768959",0.380304,0.000000