In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.634791342', '0.591852430', '0.575732249'],
 'mae score': ['130,809.389604', '141,092.873611', '136,802.354167'],
 'mse score': ['52,807,310,507.427597',
  '59,262,435,804.406944',
  '61,371,080,590.487503'],
 'r2 score': ['0.634137', '0.589414', '0.574805'],
 'mean fit time': [0.004173851013183594,
  0.008319807052612305,
  0.0071489810943603516]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.343461846', '0.562582899'],
 'mae score': ['180,492.520360', '143,169.910278'],
 'mse score': ['94,763,737,443.140488', '63,584,516,664.663940'],
 'r2 score': ['0.343451', '0.559469'],
 'mean fit time': [0.0034323692321777343, 0.0017270565032958985]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.545612545',
  '0.491413303',
  '0.545272806',
  '0.491413303'],
 'mae score': ['160,524.050161',
  '172,752.328666',
  '160,563.340413',
  '172,752.328666'],
 'mse score': ['65,672,318,948.431274',
  '73,453,714,092.510513',
  '65,725,955,326.849693',
  '73,453,714,092.510513'],
 'r2 score': ['0.545004', '0.491093', '0.544633', '0.491093'],
 'mean fit time': [0.0054107666015625,
  0.0010268211364746094,
  0.0014832973480224609,
  0.0014412403106689453]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model'],
 'explained variance score': ['0.545617450',
  '0.491221574',
  '0.538254826',
  '0.491221574'],
 'mae score': ['160,520.289055',
  '172,847.691004',
  '160,676.841288',
  '172,847.691004'],
 'mse score': ['65,667,385,122.887230',
  '73,478,487,488.626022',
  '66,710,049,883.341255',
  '73,478,487,488.626022'],
 'r2 score': ['0.545039', '0.490921', '0.537815', '0.490921'],
 'mean fit time': [0.005930471420288086,
  0.004866313934326172,
  0.003883028030395508,
  0.0014881134033203126]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.545612545',
  '0.491320646',
  '0.545143924',
  '0.491320646'],
 'mae score': ['160,524.050161',
  '172,549.271661',
  '160,357.176579',
  '172,549.271661'],
 'mse score': ['65,672,318,948.447388',
  '73,466,051,698.183502',
  '65,743,200,349.344940',
  '73,466,051,698.183502'],
 'r2 score': ['0.545004', '0.491007', '0.544513', '0.491007'],
 'mean fit time': [0.0008847236633300782,
  0.0021860599517822266,
  0.0018239021301269531,
  0.001645660400390625]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree Best Params,0.525465856,"161,667.633996","76,497,959,521.268478",0.524659,0.009398
Recursive Feature Elimination,0.437692147,"168,477.035464","90,588,408,113.372543",0.437104,0.033879
Sequential Feature Selector,0.300629820,"197,605.994537","112,633,815,122.929260",0.300119,0.028026

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.349622246,"198,155.631328","104,717,797,434.450089",0.349308,0.006885
Sequential Feature Selector,0.440855760,"179,060.379168","90,001,770,079.824097",0.440750,0.005907

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.347887513,"204,367.794129","104,946,356,936.655273",0.347888,0.791030
Select From Model,0.335563247,"205,646.105541","106,931,453,467.396774",0.335553,0.003134
Sequential Feature Selector,0.388513446,"203,265.350341","98,409,733,123.653152",0.388505,0.010194
Recursive Feature Elimination,0.335563247,"205,646.105541","106,931,453,467.396774",0.335553,0.011482

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.346786499,"204,740.754227","105,123,625,743.854507",0.346786,0.005181
Recursive Feature Elimination,0.334450640,"206,062.920926","107,111,355,523.268112",0.334435,0.003127
Sequential Feature Selector,0.387383741,"203,623.977010","98,590,934,619.739548",0.387379,0.006636
Select From Model,0.334450640,"206,062.920926","107,111,355,523.268112",0.334435,0.005456

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.347887513,"204,367.794129","104,946,356,936.655319",0.347888,0.004272
Select From Model,0.335608839,"205,621.117607","106,924,114,715.181747",0.335598,0.002341
Sequential Feature Selector,0.349340465,"203,708.056562","104,713,644,756.342804",0.349334,0.003336
Recursive Feature Elimination,0.335608839,"205,621.117607","106,924,114,715.181747",0.335598,0.001648