In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.697195714', '0.561655488', '0.532701790'],
 'mae score': ['238,327.094417', '277,522.727015', '279,925.113928'],
 'mse score': ['236,307,008,414.936371',
  '341,829,607,356.636108',
  '364,418,243,126.586853'],
 'r2 score': ['0.696972', '0.561655', '0.532688'],
 'mean fit time': [0.019043588638305665,
  0.05276641845703125,
  0.061376094818115234]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.125801844', '0.493901989'],
 'mae score': ['487,154.677635', '298,219.625265'],
 'mse score': ['682,109,607,522.214478', '394,877,754,545.682373'],
 'r2 score': ['0.125297', '0.493628'],
 'mean fit time': [0.008998346328735352, 0.011361646652221679]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.296417526',
  '0.279598709',
  '0.238837419',
  '0.296417762'],
 'mae score': ['440,888.423623',
  '441,367.727712',
  '462,734.180857',
  '440,887.448561'],
 'mse score': ['548,779,983,486.693726',
  '561,909,688,322.529297',
  '593,797,968,074.278320',
  '548,779,726,477.089722'],
 'r2 score': ['0.296272', '0.279435', '0.238543', '0.296272'],
 'mean fit time': [0.7416380882263184,
  0.010617733001708984,
  0.01930990219116211,
  0.0208864688873291]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model'],
 'explained variance score': ['0.294563780',
  '0.294543577',
  '0.236467604',
  '0.277845721'],
 'mae score': ['440,797.416612',
  '440,788.298224',
  '463,438.692196',
  '440,910.013906'],
 'mse score': ['550,208,584,070.607178',
  '550,225,732,459.209839',
  '595,623,350,817.820801',
  '563,260,011,757.697021'],
 'r2 score': ['0.294440', '0.294418', '0.236202', '0.277703'],
 'mean fit time': [0.004278945922851563,
  0.007029008865356445,
  0.005264425277709961,
  0.007382011413574219]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.296428194',
  '0.279605820',
  '0.296057989',
  '0.296057989'],
 'mae score': ['440,863.339725',
  '441,349.215152',
  '440,806.949119',
  '440,806.949119'],
 'mse score': ['548,771,706,969.938110',
  '561,904,158,591.280029',
  '549,063,929,595.034119',
  '549,063,929,595.034119'],
 'r2 score': ['0.296282', '0.279442', '0.295908', '0.295908'],
 'mean fit time': [0.0016129493713378906, 0.0, 0.0, 0.0032087326049804687]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree Best Params,0.697195714,"238,327.094417","236,307,008,414.936371",0.696972,0.019044
Recursive Feature Elimination,0.561655488,"277,522.727015","341,829,607,356.636108",0.561655,0.052766
Sequential Feature Selector,0.532701790,"279,925.113928","364,418,243,126.586853",0.532688,0.061376

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.125801844,"487,154.677635","682,109,607,522.214478",0.125297,0.008998
Sequential Feature Selector,0.493901989,"298,219.625265","394,877,754,545.682373",0.493628,0.011362

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.296417526,"440,888.423623","548,779,983,486.693726",0.296272,0.741638
Select From Model,0.279598709,"441,367.727712","561,909,688,322.529297",0.279435,0.010618
Sequential Feature Selector,0.238837419,"462,734.180857","593,797,968,074.278320",0.238543,0.019310
Recursive Feature Elimination,0.296417762,"440,887.448561","548,779,726,477.089722",0.296272,0.020886

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.294563780,"440,797.416612","550,208,584,070.607178",0.294440,0.004279
Recursive Feature Elimination,0.294543577,"440,788.298224","550,225,732,459.209839",0.294418,0.007029
Sequential Feature Selector,0.236467604,"463,438.692196","595,623,350,817.820801",0.236202,0.005264
Select From Model,0.277845721,"440,910.013906","563,260,011,757.697021",0.277703,0.007382

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.296428194,"440,863.339725","548,771,706,969.938110",0.296282,0.001613
Select From Model,0.279605820,"441,349.215152","561,904,158,591.280029",0.279442,0.000000
Sequential Feature Selector,0.296057989,"440,806.949119","549,063,929,595.034119",0.295908,0.000000
Recursive Feature Elimination,0.296057989,"440,806.949119","549,063,929,595.034119",0.295908,0.003209