In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.551812072', '0.579610470', '0.586577140'],
 'mae score': ['259,135.814821', '251,680.391304', '247,850.927536'],
 'mse score': ['186,150,467,078.847839',
  '173,998,244,815.913055',
  '171,488,457,095.463776'],
 'r2 score': ['0.550242', '0.579603', '0.585667'],
 'mean fit time': [0.0025044918060302735,
  0.0027576446533203124,
  0.003156423568725586]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.214468733', '0.247992173'],
 'mae score': ['399,520.133836', '334,485.117391'],
 'mse score': ['325,708,600,194.466553', '311,320,787,065.097656'],
 'r2 score': ['0.213055', '0.247818'],
 'mean fit time': [0.00010552406311035157, 0.002246236801147461]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.303192778',
  '0.296070715',
  '0.294674816',
  '0.296070715'],
 'mae score': ['357,796.087601',
  '366,423.677555',
  '352,327.137421',
  '366,423.677555'],
 'mse score': ['291,145,759,939.069458',
  '292,804,232,133.222351',
  '295,496,998,432.123352',
  '292,804,232,133.222351'],
 'r2 score': ['0.296562', '0.292555', '0.286049', '0.292555'],
 'mean fit time': [0.005556774139404297,
  0.0016015529632568359,
  0.0,
  0.002901506423950195]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model'],
 'explained variance score': ['0.307475145',
  '0.298073500',
  '0.299425071',
  '0.298073500'],
 'mae score': ['356,429.646998',
  '365,516.786749',
  '350,164.524669',
  '365,516.786749'],
 'mse score': ['289,292,343,473.604858',
  '291,944,096,406.499634',
  '293,431,360,859.112000',
  '291,944,096,406.499634'],
 'r2 score': ['0.301040', '0.294634', '0.291040', '0.294634'],
 'mean fit time': [0.00219573974609375,
  0.0029489994049072266,
  0.0,
  0.0012024879455566407]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.303104175',
  '0.296042831',
  '0.305222920',
  '0.296042831'],
 'mae score': ['357,804.715388',
  '366,630.711880',
  '357,217.130877',
  '366,630.711880'],
 'mse score': ['291,126,387,380.951111',
  '292,760,087,656.456543',
  '290,201,937,539.341125',
  '292,760,087,656.456543'],
 'r2 score': ['0.296609', '0.292662', '0.298843', '0.292662'],
 'mean fit time': [0.002093935012817383,
  0.0006600856781005859,
  0.0004673004150390625,
  0.0022357940673828126]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree Best Params,0.551812072,"259,135.814821","186,150,467,078.847839",0.550242,0.002504
Recursive Feature Elimination,0.579610470,"251,680.391304","173,998,244,815.913055",0.579603,0.002758
Sequential Feature Selector,0.586577140,"247,850.927536","171,488,457,095.463776",0.585667,0.003156

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.214468733,"399,520.133836","325,708,600,194.466553",0.213055,0.000106
Sequential Feature Selector,0.247992173,"334,485.117391","311,320,787,065.097656",0.247818,0.002246

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.303192778,"357,796.087601","291,145,759,939.069458",0.296562,0.005557
Select From Model,0.296070715,"366,423.677555","292,804,232,133.222351",0.292555,0.001602
Sequential Feature Selector,0.294674816,"352,327.137421","295,496,998,432.123352",0.286049,0.000000
Recursive Feature Elimination,0.296070715,"366,423.677555","292,804,232,133.222351",0.292555,0.002902

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.307475145,"356,429.646998","289,292,343,473.604858",0.301040,0.002196
Recursive Feature Elimination,0.298073500,"365,516.786749","291,944,096,406.499634",0.294634,0.002949
Sequential Feature Selector,0.299425071,"350,164.524669","293,431,360,859.112000",0.291040,0.000000
Select From Model,0.298073500,"365,516.786749","291,944,096,406.499634",0.294634,0.001202

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.303104175,"357,804.715388","291,126,387,380.951111",0.296609,0.002094
Select From Model,0.296042831,"366,630.711880","292,760,087,656.456543",0.292662,0.000660
Sequential Feature Selector,0.305222920,"357,217.130877","290,201,937,539.341125",0.298843,0.000467
Recursive Feature Elimination,0.296042831,"366,630.711880","292,760,087,656.456543",0.292662,0.002236