In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.397918613', '0.397918613', '0.411193064'],
 'mae score': ['204,500.000000', '204,500.000000', '233,500.000000'],
 'mse score': ['106,688,833,333.333328',
  '106,688,833,333.333328',
  '93,894,833,333.333328'],
 'r2 score': ['0.049081', '0.049081', '0.163114'],
 'mean fit time': [0.00052947998046875,
  0.0013878822326660156,
  0.002211189270019531]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.379466690', '0.332167653'],
 'mae score': ['239,055.555556', '260,233.333333'],
 'mse score': ['106,805,722,222.222229', '131,682,886,666.666672'],
 'r2 score': ['0.048039', '-0.173692'],
 'mean fit time': [0.0018405437469482422, 0.000194549560546875]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.722211577',
  '0.040543442',
  '0.732355225',
  '0.040543442'],
 'mae score': ['139,346.900073',
  '309,976.997844',
  '135,490.252806',
  '309,976.997844'],
 'mse score': ['34,207,400,479.922718',
  '117,436,699,657.530197',
  '33,387,642,010.595226',
  '117,436,699,657.530197'],
 'r2 score': ['0.695109', '-0.046715', '0.702415', '-0.046715'],
 'mean fit time': [0.0001544952392578125,
  0.0018259048461914062,
  0.003058338165283203,
  0.0023864269256591796]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model',
  'Polynomial Features'],
 'explained variance score': ['0.666524546',
  '0.009311623',
  '0.666235813',
  '0.009311623',
  '0.678416304'],
 'mae score': ['162,479.931443',
  '315,441.623106',
  '160,647.206528',
  '315,441.623106',
  '158,404.295765'],
 'mse score': ['40,134,382,207.780304',
  '120,207,665,746.763504',
  '40,374,469,215.238701',
  '120,207,665,746.763504',
  '39,134,925,847.592827'],
 'r2 score': ['0.642282', '-0.071413', '0.640142', '-0.071413', '0.651190'],
 'mean fit time': [0.0016257286071777344,
  0.0018158435821533203,
  0.0018278598785400391,
  0.0020148754119873047,
  0.0]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.708134530',
  '0.109790087',
  '0.702583296',
  '0.109790087'],
 'mae score': ['144,137.211300',
  '291,933.082296',
  '147,266.128498',
  '291,933.082296'],
 'mse score': ['36,105,212,599.929771',
  '126,769,196,633.604797',
  '36,346,560,328.843964',
  '126,769,196,633.604797'],
 'r2 score': ['0.678194', '-0.129896', '0.676043', '-0.129896'],
 'mean fit time': [0.001119089126586914, 0.0, 0.0, 0.0013049125671386718]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree Best Params,0.525465856,"161,667.633996","76,497,959,521.268478",0.524659,0.009398
Recursive Feature Elimination,0.437692147,"168,477.035464","90,588,408,113.372543",0.437104,0.033879
Sequential Feature Selector,0.300629820,"197,605.994537","112,633,815,122.929260",0.300119,0.028026

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.349622246,"198,155.631328","104,717,797,434.450089",0.349308,0.006885
Sequential Feature Selector,0.440855760,"179,060.379168","90,001,770,079.824097",0.440750,0.005907

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.347887513,"204,367.794129","104,946,356,936.655273",0.347888,0.791030
Select From Model,0.335563247,"205,646.105541","106,931,453,467.396774",0.335553,0.003134
Sequential Feature Selector,0.388513446,"203,265.350341","98,409,733,123.653152",0.388505,0.010194
Recursive Feature Elimination,0.335563247,"205,646.105541","106,931,453,467.396774",0.335553,0.011482

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.346786499,"204,740.754227","105,123,625,743.854507",0.346786,0.005181
Recursive Feature Elimination,0.334450640,"206,062.920926","107,111,355,523.268112",0.334435,0.003127
Sequential Feature Selector,0.387383741,"203,623.977010","98,590,934,619.739548",0.387379,0.006636
Select From Model,0.334450640,"206,062.920926","107,111,355,523.268112",0.334435,0.005456

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.347887513,"204,367.794129","104,946,356,936.655319",0.347888,0.004272
Select From Model,0.335608839,"205,621.117607","106,924,114,715.181747",0.335598,0.002341
Sequential Feature Selector,0.349340465,"203,708.056562","104,713,644,756.342804",0.349334,0.003336
Recursive Feature Elimination,0.335608839,"205,621.117607","106,924,114,715.181747",0.335598,0.001648