In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.501674592', '0.514795486', '0.597179373'],
 'mae score': ['166,463.961006', '163,732.906667', '156,544.361039'],
 'mse score': ['57,812,869,628.607346',
  '56,207,151,271.024651',
  '47,601,584,178.663040'],
 'r2 score': ['0.498992', '0.512907', '0.587483'],
 'mean fit time': [0.0, 0.0, 0.0]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.607413347', '0.611387211'],
 'mae score': ['150,617.469697', '130,687.363636'],
 'mse score': ['45,316,206,315.597481', '46,227,609,140.630547'],
 'r2 score': ['0.607289', '0.599390'],
 'mean fit time': [0.0018007278442382813, 0.0010866641998291016]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.642435253',
  '0.632635341',
  '0.662632458',
  '0.632635341'],
 'mae score': ['137,358.113378',
  '138,911.240033',
  '134,201.068416',
  '138,911.240033'],
 'mse score': ['41,299,394,421.835884',
  '42,403,155,346.108559',
  '38,987,111,740.271225',
  '42,403,155,346.108559'],
 'r2 score': ['0.642098', '0.632533', '0.662137', '0.632533'],
 'mean fit time': [0.0038252830505371093,
  0.0028829097747802733,
  0.0029617786407470704,
  0.001983785629272461]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model',
  'Polynomial Features'],
 'explained variance score': ['0.649706541',
  '0.613840083',
  '0.648231125',
  '0.613840083',
  '0.664064648'],
 'mae score': ['136,091.615748',
  '140,674.889457',
  '136,592.357816',
  '140,674.889457',
  '133,873.082402'],
 'mse score': ['40,441,100,802.448448',
  '44,560,912,498.793678',
  '40,614,067,344.978828',
  '44,560,912,498.793678',
  '38,812,855,946.646751'],
 'r2 score': ['0.649536', '0.613834', '0.648037', '0.613834', '0.663647'],
 'mean fit time': [0.00142669677734375,
  0.0,
  0.0,
  0.002927398681640625,
  0.00317234992980957]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.657814964',
  '0.626006990',
  '0.658946829',
  '0.626006990'],
 'mae score': ['135,156.243797',
  '140,183.139604',
  '135,140.667179',
  '140,183.139604'],
 'mse score': ['39,553,871,091.152069',
  '43,186,062,885.362053',
  '39,425,424,289.190018',
  '43,186,062,885.362053'],
 'r2 score': ['0.657225', '0.625748', '0.658338', '0.625748'],
 'mean fit time': [0.0013741493225097657,
  0.0012980461120605468,
  0.0021634578704833986,
  0.0]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree,0.501674592,"166,463.961006","57,812,869,628.607346",0.498992,0.0
Recursive Feature Elimination,0.514795486,"163,732.906667","56,207,151,271.024651",0.512907,0.0
Sequential Feature Selector,0.597179373,"156,544.361039","47,601,584,178.663040",0.587483,0.0

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.607413347,"150,617.469697","45,316,206,315.597481",0.607289,0.001801
Sequential Feature Selector,0.611387211,"130,687.363636","46,227,609,140.630547",0.599390,0.001087

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.642435253,"137,358.113378","41,299,394,421.835884",0.642098,0.003825
Select From Model,0.632635341,"138,911.240033","42,403,155,346.108559",0.632533,0.002883
Sequential Feature Selector,0.662632458,"134,201.068416","38,987,111,740.271225",0.662137,0.002962
Recursive Feature Elimination,0.632635341,"138,911.240033","42,403,155,346.108559",0.632533,0.001984

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.649706541,"136,091.615748","40,441,100,802.448448",0.649536,0.001427
Recursive Feature Elimination,0.613840083,"140,674.889457","44,560,912,498.793678",0.613834,0.000000
Sequential Feature Selector,0.648231125,"136,592.357816","40,614,067,344.978828",0.648037,0.000000
Select From Model,0.613840083,"140,674.889457","44,560,912,498.793678",0.613834,0.002927
Polynomial Features,0.664064648,"133,873.082402","38,812,855,946.646751",0.663647,0.003172

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.657814964,"135,156.243797","39,553,871,091.152069",0.657225,0.001374
Select From Model,0.626006990,"140,183.139604","43,186,062,885.362053",0.625748,0.001298
Sequential Feature Selector,0.658946829,"135,140.667179","39,425,424,289.190018",0.658338,0.002163
Recursive Feature Elimination,0.626006990,"140,183.139604","43,186,062,885.362053",0.625748,0.000000