In [1]:
import pandas as pd

In [2]:
decision_tree_df = pd.DataFrame({'model': ['Decision Tree Best Params',
  'Recursive Feature Elimination',
  'Sequential Feature Selector'],
 'explained variance score': ['0.525465856', '0.437692147', '0.300629820'],
 'mae score': ['161,667.633996', '168,477.035464', '197,605.994537'],
 'mse score': ['76,497,959,521.268478',
  '90,588,408,113.372543',
  '112,633,815,122.929260'],
 'r2 score': ['0.524659', '0.437104', '0.300119'],
 'mean fit time': [0.009398412704467774,
  0.033878517150878903,
  0.028026437759399413]}).set_index('model')

In [3]:
knn_df = pd.DataFrame({'model': ['KNN Best Params', 'Sequential Feature Selector'],
 'explained variance score': ['0.349622246', '0.440855760'],
 'mae score': ['198,155.631328', '179,060.379168'],
 'mse score': ['104,717,797,434.450089', '90,001,770,079.824097'],
 'r2 score': ['0.349308', '0.440750'],
 'mean fit time': [0.0068851947784423825, 0.005906915664672852]}).set_index('model')

In [4]:
lasso_df = pd.DataFrame({'model': ['Lasso Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.347887513',
  '0.335563247',
  '0.388513446',
  '0.335563247'],
 'mae score': ['204,367.794129',
  '205,646.105541',
  '203,265.350341',
  '205,646.105541'],
 'mse score': ['104,946,356,936.655273',
  '106,931,453,467.396774',
  '98,409,733,123.653152',
  '106,931,453,467.396774'],
 'r2 score': ['0.347888', '0.335553', '0.388505', '0.335553'],
 'mean fit time': [0.7910299301147461,
  0.00313420295715332,
  0.01019439697265625,
  0.011481761932373047]}).set_index('model')

In [5]:
linear_df = pd.DataFrame({'model': ['Linear Regression',
  'Recursive Feature Elimination',
  'Sequential Feature Selector',
  'Select From Model'],
 'explained variance score': ['0.346786499',
  '0.334450640',
  '0.387383741',
  '0.334450640'],
 'mae score': ['204,740.754227',
  '206,062.920926',
  '203,623.977010',
  '206,062.920926'],
 'mse score': ['105,123,625,743.854507',
  '107,111,355,523.268112',
  '98,590,934,619.739548',
  '107,111,355,523.268112'],
 'r2 score': ['0.346786', '0.334435', '0.387379', '0.334435'],
 'mean fit time': [0.005180978775024414,
  0.0031272411346435548,
  0.006636285781860351,
  0.005456113815307617]}).set_index('model')

In [6]:
ridge_df = pd.DataFrame({'model': ['Ridge Best Params',
  'Select From Model',
  'Sequential Feature Selector',
  'Recursive Feature Elimination'],
 'explained variance score': ['0.347887513',
  '0.335608839',
  '0.349340465',
  '0.335608839'],
 'mae score': ['204,367.794129',
  '205,621.117607',
  '203,708.056562',
  '205,621.117607'],
 'mse score': ['104,946,356,936.655319',
  '106,924,114,715.181747',
  '104,713,644,756.342804',
  '106,924,114,715.181747'],
 'r2 score': ['0.347888', '0.335598', '0.349334', '0.335598'],
 'mean fit time': [0.0042721271514892575,
  0.002340555191040039,
  0.003335714340209961,
  0.0016481399536132813]}).set_index('model')

In [7]:
decision_tree_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Decision Tree Best Params,0.525465856,"161,667.633996","76,497,959,521.268478",0.524659,0.009398
Recursive Feature Elimination,0.437692147,"168,477.035464","90,588,408,113.372543",0.437104,0.033879
Sequential Feature Selector,0.300629820,"197,605.994537","112,633,815,122.929260",0.300119,0.028026

In [8]:
knn_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
KNN Best Params,0.349622246,"198,155.631328","104,717,797,434.450089",0.349308,0.006885
Sequential Feature Selector,0.440855760,"179,060.379168","90,001,770,079.824097",0.440750,0.005907

In [9]:
lasso_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Lasso Best Params,0.347887513,"204,367.794129","104,946,356,936.655273",0.347888,0.791030
Select From Model,0.335563247,"205,646.105541","106,931,453,467.396774",0.335553,0.003134
Sequential Feature Selector,0.388513446,"203,265.350341","98,409,733,123.653152",0.388505,0.010194
Recursive Feature Elimination,0.335563247,"205,646.105541","106,931,453,467.396774",0.335553,0.011482

In [10]:
linear_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Linear Regression,0.346786499,"204,740.754227","105,123,625,743.854507",0.346786,0.005181
Recursive Feature Elimination,0.334450640,"206,062.920926","107,111,355,523.268112",0.334435,0.003127
Sequential Feature Selector,0.387383741,"203,623.977010","98,590,934,619.739548",0.387379,0.006636
Select From Model,0.334450640,"206,062.920926","107,111,355,523.268112",0.334435,0.005456

In [11]:
ridge_df

,explained variance score,mae score,mse score,r2 score,mean fit time
model,,,,,
Ridge Best Params,0.347887513,"204,367.794129","104,946,356,936.655319",0.347888,0.004272
Select From Model,0.335608839,"205,621.117607","106,924,114,715.181747",0.335598,0.002341
Sequential Feature Selector,0.349340465,"203,708.056562","104,713,644,756.342804",0.349334,0.003336
Recursive Feature Elimination,0.335608839,"205,621.117607","106,924,114,715.181747",0.335598,0.001648